# Generated by Django 4.0.2 on 2022-03-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codeadh', models.CharField(max_length=10, unique=True)),
                ('nomadh', models.CharField(max_length=100)),
                ('prenomadh', models.CharField(max_length=100)),
                ('datenaiss', models.DateField(blank=True, null=True)),
                ('lieunaiss', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'adherent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Benevole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombene', models.CharField(max_length=100)),
                ('prenombene', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'benevole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Decaissement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numtrans', models.CharField(max_length=10, unique=True)),
                ('datetrans', models.DateField()),
                ('naturedep', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'decaissement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_document', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentEmpreint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_empreint', models.DateField(blank=True, null=True)),
                ('rendu', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'document_empreint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_document', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'document_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numtrans', models.CharField(max_length=10, unique=True)),
                ('datetrans', models.DateField()),
                ('sourceenc', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'encaissement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_evenement', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'evenement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvenementParticipation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cancelled', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'evenement_participation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvenementType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_evenement', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'evenement_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codeforma', models.CharField(max_length=100, unique=True)),
                ('nomform', models.CharField(max_length=100)),
                ('desform', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'formation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormationSalles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codesalle', models.CharField(max_length=100, unique=True)),
                ('nomsalle', models.CharField(max_length=100)),
                ('capacitesalle', models.IntegerField()),
            ],
            options={
                'db_table': 'formation_salles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormationSession',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codesession', models.CharField(max_length=100, unique=True)),
                ('datesession', models.DateField()),
            ],
            options={
                'db_table': 'formation_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormationSessionInscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'formation_session_inscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sallemachine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codesallem', models.CharField(max_length=100, unique=True)),
                ('nomsallem', models.CharField(max_length=100)),
                ('capacitesallem', models.IntegerField()),
            ],
            options={
                'db_table': 'sallemachine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SallemachineReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creneau', models.CharField(max_length=100)),
                ('date_creneau', models.DateField()),
            ],
            options={
                'db_table': 'sallemachine_reservation',
                'managed': False,
            },
        ),
    ]
